name: Coverage

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --legacy-peer-deps
    - name: Generating Coverage information
      run: npm run coverage-test
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}