# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --legacy-peer-deps
    - run: npm test
    - name: Send Slack Notification on Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: e13
        SLACK_COLOR: "#9e2a2b"
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: "Failed tests"
        SLACK_TITLE: Failed execution
        SLACK_USERNAME: Test
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Send Slack Notification on Success
      if: ${{ !failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: e13
        SLACK_COLOR: "#7CFC00"
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: "Successful tests"
        SLACK_TITLE: Successful tests
        SLACK_USERNAME: Test
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Build React App
      run: CI=false npm run build
    - name: Deploy to Surge
      run: surge ./happyharvest/build https://ullstwe13.surge.sh/ --token ${{ secrets.SURGE_SECRET }}

